# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          curl -o allure-2.14.0.zip -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.14.0/allure-commandline-2.14.0.zip
          unzip allure-2.14.0.zip -d allure-2.14.0
          echo "PATH=\$PATH:$PWD/allure-2.14.0/bin" >> $GITHUB_ENV

      - name: Run tests with pytest
        run: pytest --alluredir=./allure-results

      - name: Generate Allure report
        run: |
          export PATH=$PATH:$PWD/allure-2.14.0/bin
          allure generate ./allure-results --clean -o ./allure-report
